#!/usr/bin/env python3
"""Probe-based observable CSG quotient checker.

Replaces the old weighted-distance matcher. The acceptance criterion is a
*per-probe agreement vector*, not a thresholded scalar:

    PASS  <=>  every HARD probe agrees under the best object-role mapping.

The scalar ``distance`` is retained as a graded diagnostic / curriculum signal,
but it is no longer the gate. This matches the math's definition (``w ~ w'``
iff all probes agree) and removes the "honest distance-0 is unsatisfiable"
trap, because confidence, planner-view, and temporal-edge differences are
normalized away in ``canon`` before any probe runs.

Probe split (user decision):
  HARD  object_carrier, initial_state, terminal_state, relation_transitions,
        articulation_transitions, event_order, goal_satisfaction
  SOFT  contact_word, object_trajectory, contact_evidence
  contact_word is promoted to HARD iff the target carries an explicit contact
  constraint, and is then compared directionally on exactly the constrained
  entity pairs (``CanonGraph.contact_word_pairs``).

V0.2 soundness revisions (second audit):
  * Probe-support gate: PASS additionally requires that the target actually
    constrained something (nonzero support on at least one task-defining
    probe). A vacuous or fully confidence-masked target no longer accepts
    every rollout (audit A1/A2).
  * event_order is an injective, order-preserving *embedding* of the target
    event sequence into the robot's, not directional pair containment — a
    single consistent in-order occurrence of the demonstrated sequence must
    exist. Duplicate event signatures can no longer satisfy arbitrary
    orderings ("ritual replay", audit A3). Accepted semantics: a messy prefix
    followed by a genuine in-order redo PASSes; causality of the achieving
    contact remains a UCV (physical_quotient.md §10.14).
  * articulation_transitions is directional (target ⊆ robot), consistent with
    the event/relation probes (audit A7).

Object-role isomorphism is solved by minimizing the *total* probe distance over
signature-compatible bijections (not a separate graph-only cost), so symmetric
objects cannot be mismatched into a spurious nonzero distance.

V0.3 object mapping (audit A6): candidate bijections come from 1-WL role
fingerprints (``_role_fingerprints``) plus a similarity-guided DFS capped at
``MatcherConfig.max_candidate_mappings``, replacing N! enumeration. Planner
goals are excluded from fingerprints (time-warp invariance; target-only).
Equal-fingerprint objects form symmetry orbits, reported via
``object_orbit_ambiguous`` / ``diagnostics['target_symmetry_orbits']``.
"""
from __future__ import annotations

import argparse
import dataclasses
import json
import math
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Any, Dict, FrozenSet, List, Mapping, Optional, Sequence, Tuple

from .canon import CanonConfig, CanonGraph, ObjectProfile, canonical_form
from .common import Json, load_json

HARD_PROBES = (
    "object_carrier",
    "initial_state",
    "terminal_state",
    "relation_transitions",
    "articulation_transitions",
    "event_presence",
    "event_order",
    "goal_satisfaction",
)
SOFT_PROBES = ("contact_word", "object_trajectory", "contact_evidence")

# Topological / containment relations that define task structure. NEAR/FAR are
# kept for init/terminal endpoints but are weaker.
STRUCTURAL_RELATIONS = {"INSIDE", "ON_TOP_OF", "OCCLUDES", "ALIGNED_WITH"}

# Relations with no meaningful subject/object orientation; compared as
# unordered pairs so phrasing direction cannot change the task class.
SYMMETRIC_RELATIONS = {"NEAR", "FAR_FROM", "TOUCHING_LIKELY", "ALIGNED_WITH"}


@dataclass
class MatcherConfig:
    position_tol_m: float = 0.03
    articulation_tol: float = 0.05
    # Object-mapping search budget: candidate bijections are generated by a
    # similarity-guided DFS over 1-WL role fingerprints (audit A6) instead of
    # N! enumeration; this caps how many complete mappings are evaluated.
    max_candidate_mappings: int = 32
    # 1-WL color-refinement rounds for role fingerprints.
    wl_rounds: int = 2
    same_class_eps: float = 1e-9
    # Vacuity gate: a target must constrain at least one task-defining probe
    # for a PASS to be meaningful (audit A1/A2).
    require_support: bool = True
    task_defining_probes: Tuple[str, ...] = (
        "goal_satisfaction", "relation_transitions", "articulation_transitions")
    # Backtracking budget for the event-order embedding search.
    embed_node_budget: int = 20000
    # Component weights for the *diagnostic* scalar only.
    weights: Dict[str, float] = field(default_factory=lambda: {
        "object_carrier": 1.0,
        "initial_state": 1.0,
        "terminal_state": 2.0,
        "relation_transitions": 2.0,
        "articulation_transitions": 1.5,
        "event_presence": 1.0,
        "event_order": 0.75,
        "goal_satisfaction": 2.0,
        "contact_word": 1.0,
        "object_trajectory": 0.75,
        "contact_evidence": 0.5,
    })
    canon: CanonConfig = field(default_factory=CanonConfig)


@dataclass
class MatchResult:
    passed: bool
    distance: float
    probe_agreement: Dict[str, bool]
    probe_distance: Dict[str, float]
    hard_probes: Tuple[str, ...]
    object_mapping: Dict[str, str]
    object_orbit_ambiguous: bool
    # How many target-side facts each probe actually checked. A probe that
    # agrees with support 0 agreed vacuously.
    probe_support: Dict[str, int] = field(default_factory=dict)
    # True when no task-defining probe had any target support; gated by
    # MatcherConfig.require_support.
    vacuous: bool = False
    diagnostics: Dict[str, Any] = field(default_factory=dict)

    # Backwards-compatible alias used by older callers / reports.
    @property
    def same_quotient_class(self) -> bool:
        return self.passed

    @property
    def component_distances(self) -> Dict[str, float]:
        return dict(self.probe_distance)

    def to_json(self) -> Json:
        return {
            "passed": self.passed,
            "distance": self.distance,
            "sameQuotientClass": self.passed,
            "probeAgreement": dict(self.probe_agreement),
            "probeDistance": dict(self.probe_distance),
            "probeSupport": dict(self.probe_support),
            "vacuous": self.vacuous,
            "hardProbes": list(self.hard_probes),
            "objectMapping": dict(self.object_mapping),
            "objectOrbitAmbiguous": self.object_orbit_ambiguous,
            "componentDistances": dict(self.probe_distance),
            "diagnostics": self.diagnostics,
        }


# -----------------------------------------------------------------------------
# Set / sequence helpers
# -----------------------------------------------------------------------------


def _jaccard(a: FrozenSet, b: FrozenSet) -> float:
    if not a and not b:
        return 0.0
    if not a or not b:
        return 1.0
    return 1.0 - len(a & b) / len(a | b)


def _remap(eid: str, mapping: Mapping[str, str]) -> str:
    if eid in ("EFFECTOR", "SCENE", ""):
        return eid
    return mapping.get(eid, eid)


def _fact(s: str, o: str, rel: str, mapping: Mapping[str, str]) -> Tuple[str, str, str]:
    """Comparable relation fact in robot id space. Symmetric relations are
    emitted with the pair sorted so phrasing direction cannot matter."""
    a, b = _remap(s, mapping), _remap(o, mapping)
    if rel in SYMMETRIC_RELATIONS:
        a, b = sorted((a, b))
    return (a, b, rel)


# -----------------------------------------------------------------------------
# Relation timeline (relation states + transition endpoints)
# -----------------------------------------------------------------------------


def _relation_timeline(g: CanonGraph) -> Dict[Tuple[str, str], List[Tuple[float, str, str, str]]]:
    """Per *unordered* object pair, the time-ordered oriented relation
    observations (t, subject, object, relation), merged from explicit relation
    states AND the independently-normalized endpoints of relation transitions.
    Keying by unordered pair keeps one timeline per pair even when phrasing
    direction varies across observations."""
    tl: Dict[Tuple[str, str], List[Tuple[float, str, str, str]]] = defaultdict(list)

    def add(t: float, s: str, o: str, rel: str) -> None:
        tl[tuple(sorted((s, o)))].append((t, s, o, rel))  # type: ignore[index]

    for f in g.relation_facts:
        add(f.t, f.subject, f.object, f.relation)
    for e in g.events:
        for (f_fact, t_fact) in e.relation_transitions:
            add(e.t_start, *f_fact)
            add(e.t_end, *t_fact)
    for pair in tl:
        tl[pair].sort(key=lambda x: (x[0], x[1], x[2], x[3]))
    return tl


def _endpoint_relations(g: CanonGraph, mapping: Mapping[str, str], which: str) -> FrozenSet[Tuple[str, str, str]]:
    """Initial (which='first') or terminal (which='last') relation per pair,
    restricted to structural+NEAR relations, with ids remapped."""
    tl = _relation_timeline(g)
    out = set()
    for pair, obs in tl.items():
        if not obs:
            continue
        _, s, o, rel = obs[0] if which == "first" else obs[-1]
        if rel in STRUCTURAL_RELATIONS or rel in {"NEAR", "FAR_FROM"}:
            out.add(_fact(s, o, rel, mapping))
    return frozenset(out)


def _articulation_endpoints(g: CanonGraph, mapping: Mapping[str, str]) -> Dict[str, Tuple[Optional[float], Optional[float], str, str]]:
    """oid -> (first_value, last_value, joint_kind, value_kind)."""
    by_oid: Dict[str, List[Any]] = defaultdict(list)
    for f in g.articulation_facts:
        by_oid[f.object_id].append(f)
    out: Dict[str, Tuple[Optional[float], Optional[float], str, str]] = {}
    for oid, facts in by_oid.items():
        facts.sort(key=lambda f: f.t)
        first = next((f.value for f in facts if f.value is not None), None)
        last = next((f.value for f in reversed(facts) if f.value is not None), None)
        out[_remap(oid, mapping)] = (first, last, facts[0].joint_kind, facts[0].value_kind)
    return out


# -----------------------------------------------------------------------------
# Probe extraction (all in the robot id space, via mapping)
# -----------------------------------------------------------------------------


def _probe_relation_transitions(g: CanonGraph, mapping: Mapping[str, str]) -> FrozenSet:
    """Set of structural relations *achieved* per pair, drawn from the merged
    relation timeline (which already includes transition endpoints).

    We deliberately compare the set of (subject, object, structural_relation)
    rather than (from, to) pairs: a coarse human transition NEAR->INSIDE and a
    fine-grained rollout NEAR->ABOVE_3D->INSIDE both achieve INSIDE(cube,tray).
    Ordering and endpoints are checked by the event_order / terminal_state /
    initial_state probes instead, so this probe is robust to fragmentation."""
    out = set()
    for _, obs in _relation_timeline(g).items():
        for (_, s, o, rel) in obs:
            if rel in STRUCTURAL_RELATIONS:
                out.add(_fact(s, o, rel, mapping))
    return frozenset(out)


def _probe_articulation_transitions(g: CanonGraph, mapping: Mapping[str, str], tol: float) -> FrozenSet:
    out = set()
    arts = _articulation_endpoints(g, mapping)
    for oid, (first, last, jk, vk) in arts.items():
        direction = "FLAT"
        if first is not None and last is not None:
            if last - first > tol:
                direction = "INCREASE"
            elif first - last > tol:
                direction = "DECREASE"
        out.add((oid, jk, vk, direction))
    # Also explicit transitions without values.
    for e in g.events:
        for (oid, jk, vk) in e.articulation_transitions:
            moid = _remap(oid, mapping)
            if not any(t[0] == moid for t in out):
                out.add((moid, jk, vk, "FLAT"))
    return frozenset(out)


def _event_sigs(g: CanonGraph, mapping: Mapping[str, str]) -> FrozenSet:
    return frozenset((e.kind, frozenset(_remap(o, mapping) for o in e.objects)) for e in g.events)


def _event_seq(g: CanonGraph, mapping: Mapping[str, str]) -> List[Tuple[float, float, Tuple]]:
    """Time-sorted (t_start, t_end, signature) event sequence in robot id space."""
    seq = [(e.t_start, e.t_end, (e.kind, frozenset(_remap(o, mapping) for o in e.objects))) for e in g.events]
    seq.sort(key=lambda x: (x[0], x[1], str(x[2])))
    return seq


def _count_ordered_pairs(seq: Sequence[Tuple[float, float, Tuple]], margin: float) -> int:
    """Number of strictly-ordered (disjoint-span) event pairs in a sequence."""
    n = 0
    for i in range(len(seq)):
        for j in range(len(seq)):
            if i != j and seq[i][1] + margin <= seq[j][0]:
                n += 1
    return n


def _embed_events(target_seq: Sequence[Tuple[float, float, Tuple]], robot_seq: Sequence[Tuple[float, float, Tuple]], margin: float, node_budget: int) -> Tuple[bool, int]:
    """Injective, signature-preserving, order-preserving embedding of the
    target event sequence into the robot event sequence.

    Returns (full_embedding_exists, greedily_embeddable_count). A full
    embedding means one consistent in-order occurrence of the demonstrated
    sequence exists in the rollout (extra robot events are fine). This
    replaces directional pair containment, which was vacuously satisfiable by
    duplicate event signatures (audit A3): a robot pair-set containing both
    (A,B) and (B,A) is not a replay of A-then-B."""
    n = len(target_seq)
    if n == 0:
        return True, 0
    preds: List[List[int]] = [[] for _ in range(n)]
    for j in range(n):
        for i in range(n):
            if i != j and target_seq[i][1] + margin <= target_seq[j][0]:
                preds[j].append(i)
    by_sig: Dict[Tuple, List[int]] = defaultdict(list)
    for idx, (_, _, sig) in enumerate(robot_seq):
        by_sig[sig].append(idx)
    for sig in by_sig:
        by_sig[sig].sort(key=lambda i: robot_seq[i][1])  # earliest-end first

    assign: List[int] = [-1] * n
    used: set = set()
    nodes = 0

    def dfs(k: int) -> bool:
        nonlocal nodes
        if k == n:
            return True
        nodes += 1
        if nodes > node_budget:
            return False
        lo = max((robot_seq[assign[p]][1] for p in preds[k]), default=-math.inf)
        for ridx in by_sig.get(target_seq[k][2], []):
            if ridx in used or robot_seq[ridx][0] < lo + margin:
                continue
            used.add(ridx)
            assign[k] = ridx
            if dfs(k + 1):
                return True
            used.discard(ridx)
            assign[k] = -1
        return False

    if dfs(0):
        return True, n

    # Greedy partial embedding for a graded distance.
    used.clear()
    assigned_end: Dict[int, float] = {}
    count = 0
    for k in range(n):
        lo = max((assigned_end[p] for p in preds[k] if p in assigned_end), default=-math.inf)
        for ridx in by_sig.get(target_seq[k][2], []):
            if ridx not in used and robot_seq[ridx][0] >= lo + margin:
                used.add(ridx)
                assigned_end[k] = robot_seq[ridx][1]
                count += 1
                break
    return False, count


def _directional_missing(target_set: FrozenSet, robot_set: FrozenSet) -> float:
    """Fraction of target facts not reproduced by the robot. Extra robot facts
    are allowed (a richer rollout is fine); missing demonstrated facts are not."""
    if not target_set:
        return 0.0
    missing = target_set - robot_set
    return len(missing) / len(target_set)


def _probe_object_carrier(g: CanonGraph, mapping: Mapping[str, str]) -> Dict[str, Tuple]:
    return {_remap(oid, mapping): g.objects[oid].hard_signature() for oid in g.relevant_objects}


def _probe_contact_word(g: CanonGraph, mapping: Mapping[str, str]) -> FrozenSet:
    """Compressed contact-mode sequence per entity pair (effector abstracted)."""
    seqs: Dict[Tuple[str, str], List[Tuple[float, str]]] = defaultdict(list)
    for c in g.contact_facts:
        a, b = sorted([_remap(c.a, mapping), _remap(c.b, mapping)])
        seqs[(a, b)].append((c.t_start, c.mode))
    out = set()
    for pair, items in seqs.items():
        items.sort(key=lambda x: x[0])
        compressed = tuple(m for i, (_, m) in enumerate(items) if i == 0 or m != items[i - 1][1])
        out.add((pair, compressed))
    return frozenset(out)


def _probe_contact_evidence(g: CanonGraph, mapping: Mapping[str, str]) -> FrozenSet:
    out = set()
    for c in g.contact_facts:
        if c.state_change_near_boundary:
            a, b = sorted([_remap(c.a, mapping), _remap(c.b, mapping)])
            out.add((a, b, "STATE_CHANGE_NEAR_BOUNDARY"))
    return frozenset(out)


def _goal_satisfaction_distance(target: CanonGraph, robot: CanonGraph, mapping: Mapping[str, str], cfg: MatcherConfig) -> float:
    """Evaluate target's HARD planner goals against robot's terminal state."""
    hard_goals = [gl for gl in target.planner_goals if gl.hard]
    if not hard_goals:
        return 0.0
    robot_terminal = _endpoint_relations(robot, {}, "last")
    robot_art = _articulation_endpoints(robot, {})
    unmet = 0
    for gl in hard_goals:
        if gl.relation:
            want = _fact(gl.subject, gl.object, gl.relation, mapping)
            if want not in robot_terminal:
                unmet += 1
        elif gl.articulation_object:
            moid = _remap(gl.articulation_object, mapping)
            ep = robot_art.get(moid)
            if ep is None or ep[1] is None or gl.target_value is None or abs(ep[1] - gl.target_value) > cfg.articulation_tol:
                unmet += 1
    return unmet / len(hard_goals)


def _trajectory_distance(target: CanonGraph, robot: CanonGraph, mapping: Mapping[str, str], cfg: MatcherConfig) -> float:
    costs = []
    for oid in target.relevant_objects:
        a = target.pose_series.get(oid, [])
        b = robot.pose_series.get(_remap(oid, mapping), [])
        if not a and not b:
            continue
        if not a or not b:
            costs.append(1.0)
            continue
        costs.append(_pose_dtw(a, b, cfg))
    return sum(costs) / len(costs) if costs else 0.0


def _pose_dtw(a: Sequence, b: Sequence, cfg: MatcherConfig) -> float:
    n, m = len(a), len(b)
    dp = [[math.inf] * (m + 1) for _ in range(n + 1)]
    dp[0][0] = 0.0
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            d = math.dist(a[i - 1][1], b[j - 1][1])
            c = 0.0 if d <= cfg.position_tol_m else min(1.0, (d - cfg.position_tol_m) / 0.25)
            dp[i][j] = c + min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1])
    return min(1.0, dp[n][m] / max(n, m))


# -----------------------------------------------------------------------------
# Per-mapping evaluation
# -----------------------------------------------------------------------------


def _evaluate_mapping(target: CanonGraph, robot: CanonGraph, mapping: Dict[str, str], cfg: MatcherConfig, hard_probes: Tuple[str, ...]) -> Tuple[Dict[str, float], Dict[str, bool], Dict[str, int]]:
    margin = cfg.canon.order_margin_s
    eps = cfg.same_class_eps

    # Object carrier: bijection covering both relevant sets with equal signatures.
    t_carrier = _probe_object_carrier(target, mapping)
    r_carrier = _probe_object_carrier(robot, {})
    if set(t_carrier) != set(r_carrier):
        carrier_d = 1.0
    else:
        mism = sum(1 for k in t_carrier if t_carrier[k] != r_carrier.get(k))
        carrier_d = mism / max(1, len(t_carrier))

    t_init = _endpoint_relations(target, mapping, "first")
    t_term = _endpoint_relations(target, mapping, "last")
    t_rtrans = _probe_relation_transitions(target, mapping)
    t_atrans = _probe_articulation_transitions(target, mapping, cfg.articulation_tol)
    t_sigs = _event_sigs(target, mapping)

    init_d = _directional_missing(t_init, _endpoint_relations(robot, {}, "first"))
    term_d = _directional_missing(t_term, _endpoint_relations(robot, {}, "last"))
    rtrans_d = _directional_missing(t_rtrans, _probe_relation_transitions(robot, {}))
    # Directional like the event/relation probes: every demonstrated
    # articulation change must be reproduced; extra robot articulation facts
    # are allowed. Conflicts are still caught because the tuple carries the
    # direction (target FLAT vs robot INCREASE on the same object = missing).
    atrans_d = _directional_missing(t_atrans, _probe_articulation_transitions(robot, {}, cfg.articulation_tol))
    # Event probes are directional: the robot must reproduce every demonstrated
    # event and ordering, but may add extra events of its own.
    presence_d = _directional_missing(t_sigs, _event_sigs(robot, {}))

    t_seq = _event_seq(target, mapping)
    r_seq = _event_seq(robot, {})
    order_support = _count_ordered_pairs(t_seq, margin)
    embedded_ok, embedded_n = _embed_events(t_seq, r_seq, margin, cfg.embed_node_budget)
    if embedded_ok:
        order_d = 0.0
    else:
        # Never report 0 on a failed embedding (greedy may count all n when
        # the DFS budget was exhausted).
        order_d = max(1.0 / max(1, len(t_seq)), (len(t_seq) - embedded_n) / max(1, len(t_seq)))

    goal_d = _goal_satisfaction_distance(target, robot, mapping, cfg)
    n_hard_goals = sum(1 for gl in target.planner_goals if gl.hard)

    t_words = _probe_contact_word(target, mapping)
    r_words = _probe_contact_word(robot, {})
    if target.contact_word_pairs:
        # Promoted: compare directionally on exactly the constrained pairs;
        # extra robot contacts on other pairs are irrelevant (audit A7).
        req = {tuple(sorted((_remap(a, mapping), _remap(b, mapping)))) for (a, b) in target.contact_word_pairs}
        t_req = frozenset(w for w in t_words if w[0] in req)
        contact_d = _directional_missing(t_req, frozenset(w for w in r_words if w[0] in req))
        contact_support = len(t_req)
    else:
        contact_d = _jaccard(t_words, r_words)
        contact_support = len(t_words)

    traj_d = _trajectory_distance(target, robot, mapping, cfg)
    t_evidence = _probe_contact_evidence(target, mapping)
    eviden_d = _jaccard(t_evidence, _probe_contact_evidence(robot, {}))

    distances = {
        "object_carrier": carrier_d,
        "initial_state": init_d,
        "terminal_state": term_d,
        "relation_transitions": rtrans_d,
        "articulation_transitions": atrans_d,
        "event_presence": presence_d,
        "event_order": order_d,
        "goal_satisfaction": goal_d,
        "contact_word": contact_d,
        "object_trajectory": traj_d,
        "contact_evidence": eviden_d,
    }
    support = {
        "object_carrier": len(t_carrier),
        "initial_state": len(t_init),
        "terminal_state": len(t_term),
        "relation_transitions": len(t_rtrans),
        "articulation_transitions": len(t_atrans),
        "event_presence": len(t_sigs),
        "event_order": order_support,
        "goal_satisfaction": n_hard_goals,
        "contact_word": contact_support,
        "object_trajectory": sum(1 for oid in target.relevant_objects if target.pose_series.get(oid)),
        "contact_evidence": len(t_evidence),
    }
    agreement = {k: (v <= eps) for k, v in distances.items()}
    return distances, agreement, support


# -----------------------------------------------------------------------------
# Object mapping via 1-WL role fingerprints (audit A6)
# -----------------------------------------------------------------------------


def _object_fact_features(g: CanonGraph, articulation_tol: float) -> Dict[str, List[Tuple[Tuple, Optional[str]]]]:
    """Per relevant object, the time-free structural facts it participates in,
    as (label, neighbor_object_or_None) pairs. Planner goals are deliberately
    excluded: they exist only on the target side and depend on no observation,
    so including them would make target/robot fingerprints incomparable and
    break time-warp invariance of the alignment."""
    feats: Dict[str, List[Tuple[Tuple, Optional[str]]]] = defaultdict(list)
    for obs in _relation_timeline(g).values():
        for (s, o, rel) in {(s, o, rel) for (_, s, o, rel) in obs}:
            if rel in SYMMETRIC_RELATIONS:
                feats[s].append((("R", rel, "sym"), o))
                feats[o].append((("R", rel, "sym"), s))
            else:
                feats[s].append((("R", rel, "subj"), o))
                feats[o].append((("R", rel, "obj"), s))
    for e in g.events:
        for oid in e.objects:
            others = [x for x in e.objects if x != oid]
            if others:
                feats[oid].extend(((("E", e.kind), other) for other in others))
            else:
                feats[oid].append((("E", e.kind), None))
    for c in g.contact_facts:
        for me, other in ((c.a, c.b), (c.b, c.a)):
            if me not in g.objects:
                continue
            if other in g.objects:
                feats[me].append((("C", c.mode), other))
            else:
                feats[me].append((("C", c.mode, other), None))
    arts = _articulation_endpoints(g, {})
    for oid, (first, last, jk, vk) in arts.items():
        direction = "FLAT"
        if first is not None and last is not None:
            if last - first > articulation_tol:
                direction = "INCREASE"
            elif first - last > articulation_tol:
                direction = "DECREASE"
        feats[oid].append((("A", jk, vk, direction), None))
    return feats


def _role_fingerprints(g: CanonGraph, articulation_tol: float, rounds: int = 2) -> Dict[str, Tuple]:
    """1-WL color refinement over the structural fact graph. Initial color is
    the hard carrier signature; each round folds in the sorted multiset of
    (fact label, neighbor color). Colors are pure structural tuples (no object
    ids), so fingerprints are directly comparable across graphs. Objects with
    equal fingerprints within one graph are role-interchangeable (an orbit)."""
    feats = _object_fact_features(g, articulation_tol)
    objs = list(g.relevant_objects)
    color: Dict[str, Tuple] = {
        o: (g.objects[o].hard_signature() if o in g.objects else ("EXT",)) for o in objs
    }

    def col(o: Optional[str]) -> Optional[Tuple]:
        if o is None:
            return None
        return color.get(o, ("EXT",))

    for _ in range(max(0, rounds)):
        color = {
            o: (color[o], tuple(sorted(((lab, col(nb)) for (lab, nb) in feats.get(o, [])), key=repr)))
            for o in objs
        }
    return color


def _feature_labels(feats: Mapping[str, List[Tuple[Tuple, Optional[str]]]], oid: str) -> Dict[Tuple, int]:
    out: Dict[Tuple, int] = defaultdict(int)
    for (lab, _) in feats.get(oid, []):
        out[lab] += 1
    return dict(out)


def _label_similarity(a: Mapping[Tuple, int], b: Mapping[Tuple, int]) -> float:
    """Multiset Jaccard over fact labels (neighbor-free), robust to the robot
    rollout being a fragmentation-refined superset of the demonstration."""
    if not a and not b:
        return 1.0
    inter = sum(min(a.get(k, 0), b.get(k, 0)) for k in set(a) | set(b))
    union = sum(max(a.get(k, 0), b.get(k, 0)) for k in set(a) | set(b))
    return inter / union if union else 1.0


def _candidate_mappings(target: CanonGraph, robot: CanonGraph, cfg: MatcherConfig) -> List[Dict[str, str]]:
    """Candidate bijections from target relevant objects to robot relevant
    objects, generated by a similarity-guided DFS over role fingerprints
    instead of N! enumeration (audit A6).

    Target objects are assigned most-constrained-first (descending fact
    degree); robot candidates must share the hard carrier signature and are
    tried in descending fact-label similarity. Equal-fingerprint objects are
    interchangeable, so the first mappings the DFS yields are the highest-
    likelihood role alignments; the search is capped at
    ``cfg.max_candidate_mappings`` complete mappings. A target object with no
    free same-signature robot object maps to itself, which the carrier probe
    then flags (same semantics as the old greedy fallback)."""
    A = target.relevant_objects
    B = robot.relevant_objects
    if not A:
        return [{}]

    t_feats = _object_fact_features(target, cfg.articulation_tol)
    r_feats = _object_fact_features(robot, cfg.articulation_tol)
    t_labels = {ao: _feature_labels(t_feats, ao) for ao in A}
    r_labels = {bo: _feature_labels(r_feats, bo) for bo in B}
    t_fp = _role_fingerprints(target, cfg.articulation_tol, cfg.wl_rounds)
    r_fp = _role_fingerprints(robot, cfg.articulation_tol, cfg.wl_rounds)

    # Most-constrained target objects first: their assignment prunes hardest.
    order = sorted(A, key=lambda o: (-sum(t_labels[o].values()), o))
    ranked: Dict[str, List[str]] = {}
    for ao in order:
        sig = target.objects[ao].hard_signature() if ao in target.objects else ("EXT",)
        cands = [bo for bo in B if (robot.objects[bo].hard_signature() if bo in robot.objects else ("EXT",)) == sig]
        ranked[ao] = sorted(
            cands,
            key=lambda bo: (
                0 if t_fp.get(ao) == r_fp.get(bo) else 1,  # exact role match first
                -_label_similarity(t_labels[ao], r_labels[bo]),
                bo,
            ),
        )

    results: List[Dict[str, str]] = []
    used: set = set()
    cur: Dict[str, str] = {}

    def dfs(i: int) -> None:
        if len(results) >= cfg.max_candidate_mappings:
            return
        if i == len(order):
            results.append(dict(cur))
            return
        ao = order[i]
        cands = [bo for bo in ranked[ao] if bo not in used]
        if not cands:
            # No free same-signature robot object: self-map so carrier flags it.
            cur[ao] = ao
            dfs(i + 1)
            del cur[ao]
            return
        for bo in cands:
            used.add(bo)
            cur[ao] = bo
            dfs(i + 1)
            used.discard(bo)
            del cur[ao]
            if len(results) >= cfg.max_candidate_mappings:
                return

    dfs(0)
    if not results:
        results.append({ao: ao for ao in A})
    return results


def _fingerprint_orbits(fp: Mapping[str, Tuple]) -> List[List[str]]:
    """Equal-fingerprint classes with more than one member (true symmetry
    orbits: their members are role-interchangeable in that graph)."""
    by_color: Dict[Tuple, List[str]] = defaultdict(list)
    for oid, color in fp.items():
        by_color[color].append(oid)
    return sorted([sorted(v) for v in by_color.values() if len(v) > 1])


def match(target_raw: Json, robot_raw: Json, cfg: Optional[MatcherConfig] = None) -> MatchResult:
    cfg = cfg or MatcherConfig()
    target = canonical_form(target_raw, role="target", cfg=cfg.canon)
    robot = canonical_form(robot_raw, role="rollout", cfg=cfg.canon)

    hard = list(HARD_PROBES)
    if target.requires_contact_word:
        hard.append("contact_word")
    hard_probes = tuple(hard)

    candidates = _candidate_mappings(target, robot, cfg)
    best: Optional[Tuple[int, float, Dict[str, str], Dict[str, float], Dict[str, bool], Dict[str, int]]] = None
    keys: List[Tuple[int, float]] = []
    for mapping in candidates:
        distances, agreement, support = _evaluate_mapping(target, robot, mapping, cfg, hard_probes)
        n_hard_agree = sum(1 for p in hard_probes if agreement[p])
        soft_d = sum(cfg.weights[k] * distances[k] for k in distances)
        keys.append((n_hard_agree, soft_d))
        key = (n_hard_agree, -soft_d)
        if best is None or key > (best[0], -best[1]):
            best = (n_hard_agree, soft_d, mapping, distances, agreement, support)

    assert best is not None
    best_agree, best_soft, mapping, distances, agreement, support = best
    # Orbit ambiguity: the best mapping is not unique. Either several evaluated
    # candidates tie on the full (hard-agreement, soft-distance) key, or the
    # target itself contains a symmetry orbit (equal role fingerprints), in
    # which case the unexplored permutations of that orbit are equivalent too.
    tied = sum(1 for (n, d) in keys if n == best_agree and abs(d - best_soft) <= cfg.same_class_eps)
    target_orbits = _fingerprint_orbits(_role_fingerprints(target, cfg.articulation_tol, cfg.wl_rounds))
    relevant_orbits = [orb for orb in target_orbits if any(o in mapping for o in orb)]
    orbit_ambiguous = (tied > 1 and len(candidates) > 1) or bool(relevant_orbits)

    # Vacuity gate (audit A1/A2): a target that constrains nothing
    # task-defining must not accept every rollout. Probe agreement with zero
    # support is agreement about nothing.
    vacuous = all(support.get(p, 0) == 0 for p in cfg.task_defining_probes)
    passed = all(agreement[p] for p in hard_probes) and not (vacuous and cfg.require_support)

    # Estimator-dependent object attributes excluded from the hard carrier
    # signature, surfaced as soft diagnostics only.
    soft_profile_mismatches = {}
    for t_oid, r_oid in mapping.items():
        tp, rp = target.objects.get(t_oid), robot.objects.get(r_oid)
        if tp and rp and (tp.geometry_kind, tp.parts) != (rp.geometry_kind, rp.parts):
            soft_profile_mismatches[f"{t_oid}->{r_oid}"] = {
                "target": [tp.geometry_kind, list(tp.parts)],
                "robot": [rp.geometry_kind, list(rp.parts)],
            }
    den = sum(cfg.weights.values())
    distance = sum(cfg.weights[k] * distances[k] for k in distances) / max(den, 1e-12)
    if distance < 1e-12:
        distance = 0.0

    return MatchResult(
        passed=passed,
        distance=distance,
        probe_agreement=agreement,
        probe_distance=distances,
        hard_probes=hard_probes,
        object_mapping=mapping,
        object_orbit_ambiguous=orbit_ambiguous,
        probe_support=support,
        vacuous=vacuous,
        diagnostics={
            "target_relevant_objects": target.relevant_objects,
            "robot_relevant_objects": robot.relevant_objects,
            "robot_observed_channels": robot.observed_channels,
            "robot_leakage": robot.leakage,
            "requires_contact_word": target.requires_contact_word,
            "contact_word_pairs": sorted(map(list, target.contact_word_pairs)),
            "n_candidate_mappings": len(candidates),
            "n_best_tied_mappings": tied,
            "target_symmetry_orbits": relevant_orbits,
            "object_profile_soft_mismatches": soft_profile_mismatches,
        },
    )


# Backwards-compatible aliases.
def match_csg_json(human_json: Json, robot_json: Json, cfg: Optional[MatcherConfig] = None) -> MatchResult:
    return match(human_json, robot_json, cfg)


def match_csg_files(human_path: str, robot_path: str, cfg: Optional[MatcherConfig] = None) -> MatchResult:
    return match(load_json(human_path), load_json(robot_path), cfg)


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="CSG probe-based quotient checker.")
    p.add_argument("target_json")
    p.add_argument("robot_json")
    p.add_argument("--json", action="store_true")
    return p.parse_args()


def main() -> None:
    args = _parse_args()
    result = match_csg_files(args.target_json, args.robot_json)
    if args.json:
        print(json.dumps(result.to_json(), indent=2, sort_keys=True))
    else:
        print(f"passed={result.passed}")
        print(f"vacuous={result.vacuous}")
        print(f"distance={result.distance:.6f}")
        print(f"object_mapping={result.object_mapping}")
        print("hard probes:")
        for p in result.hard_probes:
            print(f"  {p}: {'OK' if result.probe_agreement[p] else 'MISMATCH'} ({result.probe_distance[p]:.4f}, support={result.probe_support.get(p, 0)})")
        soft = [p for p in SOFT_PROBES if p not in result.hard_probes]
        print("soft probes:")
        for p in soft:
            print(f"  {p}: {result.probe_distance[p]:.4f}")


if __name__ == "__main__":
    main()
